### ISSUE TITLE
Stop using Jekyll

### ISSUE THREAD

**Issue by rachel-fenichel** [rachel-fenichel/blockly-samples#1549]
**Category**
gh-pages

**Proposal**

Stop using Jekyll for layout and templating for google.github.io/blockly-samples. Update the current predeploy step to create the entire web page, rather than creating the inner section of the web page and front matter.

Continue to deploy to gh-pages, just with a single build step (predeploy) rather than two (predeploy and build).

**Reasons to make this change:**
- Jekyll relies on Ruby and thus pulls in a chain of dependencies that is separate from the ones pulled in through npm. Removing it removes dependencies.
- Google removed the version of Ruby that we needed, and may make future breaking changes automatically.
- We’re primarily using Jekyll to add headers and footers around web pages that we already create and run when testing samples locally. That is, we’re doing something fairly straightforward with it. (However, note that the pages we have for running samples locally are actually different from and simpler than the versions on gh-pages.)
- We already have a pre-build step (predeploy) that prepends stuff onto the existing test pages.
- The scope of the project is small enough for Rachel to do it between meetings.

**Reasons not to make this change:**
Requires engineering time.
We currently have a build/deploy setup that works through GitHub Actions.

Maribeth’s primary goal: keep automation working for publishing.

- [x] Generate plugin pages
- [x]  Generate examples pages, which includes respecting the list of files that needs to be copied over (defined in package.json).
- [x]  Generate the index page, because its contents are currently generated from a markdown file that lists plugins/examples and links.
- [x]  Convert from sass to css.
- [x]  Fix remaining CSS issues. (Fixed in #1683)
- [x]  Remove the rest of the jekyll config. (Fixed in #1683)
- [x]  Update action for deploying to gh-pages. (Fixed in #1683)
- [x]  Remove jekyll from package.json. (Unnecessary--it wasn't there)
- [x]  Update documentation.  (Fixed in #1683)
